apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/admin.conf"
profiles:
- schedulerName: custom-scheduler
  plugins:
    filter:
      enabled:
        - name: NodeSelectorPlugin
    # score:
    #   enabled:
    #     - name: EnergyAwareScheduler

